development:
  adapter: postgresql
  encoding: utf8
  database: bizcenter
  pool: 5
  username: JFP
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: bizcenter
  pool: 5
  username: JFP
  password: 