# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

Office.delete_all

o1 = Office.create({ title_of_offer: 'BFI', full_street_address: '149 Rue St. Honoré, 75001, Paris', meters_squared: 0, cost_per_month: 1000 })
o2 = Office.create({ title_of_offer: 'REGUS', full_street_address: '27 Avenue de l\'Opera, 75001, Paris', meters_squared: 15, cost_per_month: 2100 })
o3 = Office.create({ title_of_offer: 'REGUS', full_street_address: '10 Place de Vendome, 75001, Paris', meters_squared: 15, cost_per_month: 2100 })
o4 = Office.create({ title_of_offer: 'Buro Club', full_street_address: '5 Rue de Castiglione, 75001, Paris', meters_squared: 15, cost_per_month: 1700 })
o5 = Office.create({ title_of_offer: 'Alac Etoile', full_street_address: '3 Avenue de l\'Opera, 75001, Paris', meters_squared: 15, cost_per_month: 1500 })
o6 = Office.create({ title_of_offer: 'WARF', full_street_address: '253 Rue St. Honoré, 75001, Paris', meters_squared: 14, cost_per_month: 1300 })
o7 = Office.create({ title_of_offer: 'Business Center Opera', full_street_address: '3 Avenue de l\'Opera, 75001, Paris', meters_squared: 0, cost_per_month: 800 })
o8 = Office.create({ title_of_offer: 'Access Centre d\'Affaires', full_street_address: '5 Rue de Turbigo, 75001, Paris', meters_squared: 0, cost_per_month: 700 })
o9 = Office.create({ title_of_offer: 'NCI Petits Champs', full_street_address: '58 Rue des Petits Champs, 75001, Paris', meters_squared: 0, cost_per_month: 1900 })
o10 = Office.create({ title_of_offer: 'NCI Vendome', full_street_address: '16 Place de Vendome, 75001, Paris', meters_squared: 23, cost_per_month: 2700 })

o11 = Office.create({ title_of_offer: 'NCI Cambon', full_street_address: '20 Rue de Cambon, 75001, Paris', meters_squared: 18, cost_per_month: 2600 })
o12 = Office.create({ title_of_offer: 'Bureautel', full_street_address: '332 Rue St. Honoré, 75001, Paris', meters_squared: 0, cost_per_month: 1700 })
o13 = Office.create({ title_of_offer: 'SDM', full_street_address: '14 Avenue de l\'Opera, 75001, Paris', meters_squared: 0, cost_per_month: 1780 })
o14 = Office.create({ title_of_offer: 'Le Domaine des Entrepreneurs', full_street_address: '149 Rue St. Honoré, 75001, Paris', meters_squared: 15, cost_per_month: 1500 })
o15 = Office.create({ title_of_offer: 'REGUS', full_street_address: '4 Rue de 4 Septembre, 75002, Paris', meters_squared: 0, cost_per_month: 0 })
o16 = Office.create({ title_of_offer: 'Courant d\'Affaires', full_street_address: '10 Rue de la Paix, 75002, Paris', meters_squared: 0, cost_per_month: 1300 })
o17 = Office.create({ title_of_offer: 'Multiburo Paris Chatelet', full_street_address: '52 Boulevard Sebastopol, 75003, Paris', meters_squared: 15, cost_per_month: 1500 })
o18 = Office.create({ title_of_offer: 'Espace Omega', full_street_address: '110 Boulevard Sebastopol, 75003, Paris', meters_squared: 0, cost_per_month: 1900 })
o19 = Office.create({ title_of_offer: 'Le Cardinal', full_street_address: '45 Rue du Cardinal Lemoine, 75005, Paris', meters_squared: 15, cost_per_month: 1300 })
o20 = Office.create({ title_of_offer: 'REGUS', full_street_address: '140 bis Rue de Rennes, 75006, Paris', meters_squared: 15, cost_per_month: 2000 })

o21 = Office.create({ title_of_offer: 'REGUS', full_street_address: '148 Rue de l\'Université, 75007, Paris', meters_squared: 15, cost_per_month: 2000 })
o22 = Office.create({ title_of_offer: 'REGUS', full_street_address: '103 Rue de Grenelle, 75007, Paris', meters_squared: 15, cost_per_month: 2000 })
o23 = Office.create({ title_of_offer: 'REGUS', full_street_address: '27/29 Rue Bassano, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o24 = Office.create({ title_of_offer: 'REGUS', full_street_address: '54/56 Avenue Hoche, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o25 = Office.create({ title_of_offer: 'REGUS', full_street_address: '68 Rue du Faubourg St. Honoré , 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o26 = Office.create({ title_of_offer: 'REGUS', full_street_address: '57 Rue d\'Amsterdam, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o27 = Office.create({ title_of_offer: 'REGUS', full_street_address: '72 Rue du Faubourg St. Honoré , 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o28 = Office.create({ title_of_offer: 'Buro Club', full_street_address: '6 Avenue Franklin Roosevelt, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o29 = Office.create({ title_of_offer: 'REGUS', full_street_address: '12/14 Rond Point des Champs Elysées, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o30 = Office.create({ title_of_offer: 'REGUS', full_street_address: '23 Rue Balzac, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })

o31 = Office.create({ title_of_offer: 'REGUS', full_street_address: '19 Boulevard Malsherbes, 75008, Paris', meters_squared: 15, cost_per_month: 2000 })
o32 = Office.create({ title_of_offer: 'Cap Elyséés International', full_street_address: '25 Rue de Ponthieu, 75008, Paris', meters_squared: 0, cost_per_month: 0 })
o33 = Office.create({ title_of_offer: 'DIGIDOM', full_street_address: '10 Rue de Penthiévre, 75008, Paris', meters_squared: 12, cost_per_month: 1000 })
o34 = Office.create({ title_of_offer: '91 Faubourg', full_street_address: '91 Rue du Faubourg St. Honoré, 75008, Paris', meters_squared: 14, cost_per_month: 2200 })
o35 = Office.create({ title_of_offer: 'REGUS', full_street_address: '18 Rue Pasquier, 75008, Paris', meters_squared: 0, cost_per_month: 0 })
o36 = Office.create({ title_of_offer: 'ATEAC Champs Elysées', full_street_address: '90 Avenue des Champs Elysées, 75008, Paris', meters_squared: 16, cost_per_month: 2500 })
o37 = Office.create({ title_of_offer: 'ATEAC Haussman', full_street_address: '75 Boulevard Haussman, 75008, Paris', meters_squared: 16, cost_per_month: 2500 })
o38 = Office.create({ title_of_offer: 'Inter Centre d\'Affaires', full_street_address: '10 Rue du Colisée, 75008, Paris', meters_squared: 15, cost_per_month: 1550 })
o39 = Office.create({ title_of_offer: 'Multiburo Champs Elysées', full_street_address: '121 Avenue des Champs Elysées, 75008, Paris', meters_squared: 15, cost_per_month: 1890 })
o40 = Office.create({ title_of_offer: 'Multiburo Paris Motaigne', full_street_address: '42 Avenue Montaigne, 75008, Paris', meters_squared: 0, cost_per_month: 1900 })

o41 = Office.create({ title_of_offer: 'SDM', full_street_address: '38 Rue de Berri, 75008, Paris', meters_squared: 0, cost_per_month: 1200 })
o42 = Office.create({ title_of_offer: 'New H Business', full_street_address: '8 Rue de Moscou, 75008, Paris', meters_squared: 15, cost_per_month: 750 })
o43 = Office.create({ title_of_offer: 'Office Champs Elysées', full_street_address: '63 Avenue des Champs Elysées, 75008, Paris', meters_squared: 0, cost_per_month: 0 })
o44 = Office.create({ title_of_offer: 'Eciffice', full_street_address: '66 Avenue des Champs Elysées, 75008, Paris', meters_squared: 14, cost_per_month: 1985 })
o45 = Office.create({ title_of_offer: 'Emergence', full_street_address: '5 Rue Helder, 75009, Paris', meters_squared: 15, cost_per_month: 1850 })
o46 = Office.create({ title_of_offer: 'KADRANCE', full_street_address: '48 Rue de la Bruyére, 75009, Paris', meters_squared: 12, cost_per_month: 1400 })
o47 = Office.create({ title_of_offer: 'REGUS', full_street_address: '26/28 Rue de Londres, 75009, Paris', meters_squared: 15, cost_per_month: 1500 })
o48 = Office.create({ title_of_offer: 'Multiburo Paris Opera', full_street_address: '13/15 Rue de Taitbout, 75009, Paris', meters_squared: 0, cost_per_month: 0 })
o49 = Office.create({ title_of_offer: 'SDM', full_street_address: '8 Rue du Faubourg Poissoniére, 75010, Paris', meters_squared: 0, cost_per_month: 0 })
o50 = Office.create({ title_of_offer: 'Buro Club', full_street_address: '75/77 Avenue Parmentier, 75011, Paris', meters_squared: 15, cost_per_month: 1400 })

o51 = Office.create({ title_of_offer: 'ITER', full_street_address: '33 Avenue Phillipe Auguste, 75011, Paris', meters_squared: 15, cost_per_month: 550 })
o52 = Office.create({ title_of_offer: 'NCI', full_street_address: '20/22 Rue des Petits Hotels, 75010, Paris', meters_squared: 17, cost_per_month: 1700 })
o53 = Office.create({ title_of_offer: 'REGUS', full_street_address: 'Avenue Ledru Rollin, 75012, Paris', meters_squared: 15, cost_per_month: 1500 })
o54 = Office.create({ title_of_offer: 'SDM', full_street_address: '21 Rue Fécamp, 75012, Paris', meters_squared: 11, cost_per_month: 750 })
o55 = Office.create({ title_of_offer: 'Multiburo Gare de Lyon', full_street_address: '4 Place Louis Armand Tour de l\'Horloge, 75012, Paris', meters_squared: 15, cost_per_month: 1500 })
o56 = Office.create({ title_of_offer: 'REGUS Paris Axe France', full_street_address: '118/122 Avenue de France, 75013, Paris', meters_squared: 15, cost_per_month: 1500 })
o57 = Office.create({ title_of_offer: 'ALTER EGO', full_street_address: '149 Avenue du Maine, 75014, Paris', meters_squared: 0, cost_per_month: 0 })
o58 = Office.create({ title_of_offer: 'Le 30', full_street_address: '30 Boulevard Pasteur, 75015, Paris', meters_squared: 12, cost_per_month: 900 })
o59 = Office.create({ title_of_offer: 'CIDES', full_street_address: '59 Avenue Victor Hugo, 75016, Paris', meters_squared: 25, cost_per_month: 3000 })
o60 = Office.create({ title_of_offer: 'ATEAC Paris', full_street_address: '33 Avenue du Maine, 75015, Paris', meters_squared: 16, cost_per_month: 2800 })

o61 = Office.create({ title_of_offer: 'REGUS', full_street_address: '7 Place d\'Iena, 75016, Paris', meters_squared: 0, cost_per_month: 0 })
o62 = Office.create({ title_of_offer: 'Au 17', full_street_address: '17 Rue Dumont d\'Hurville, 75016, Paris', meters_squared: 18, cost_per_month: 2000 })
o63 = Office.create({ title_of_offer: 'ATEAC Paris Iena', full_street_address: '28 Rue de l\'Hamiral Hamelin, 75016, Paris', meters_squared: 16, cost_per_month: 2500 })
o64 = Office.create({ title_of_offer: 'SDM', full_street_address: '55 Avenue Marceau, 75016, Paris', meters_squared: 15, cost_per_month: 1500 })
o65 = Office.create({ title_of_offer: 'REGUS', full_street_address: '27/29 Rue Raffet, 75016, Paris', meters_squared: 0, cost_per_month: 850 })
o66 = Office.create({ title_of_offer: 'REGUS', full_street_address: '6 Rue Duret, 75016, Paris', meters_squared: 0, cost_per_month: 0 })
o67 = Office.create({ title_of_offer: 'Buro Club', full_street_address: '7 Rue Léo Deslibes, 75016, Paris', meters_squared: 15, cost_per_month: 2100 })
o68 = Office.create({ title_of_offer: 'ATEAC Paris Trocadero', full_street_address: '112 Avenue Kleber, 75016, Paris', meters_squared: 0, cost_per_month: 0 })
o69 = Office.create({ title_of_offer: 'Multiburo Paris Trocadero', full_street_address: '14 Avenue d\'Eylau, 75016, Paris', meters_squared: 15, cost_per_month: 1890 })
o70 = Office.create({ title_of_offer: 'Multiburo Paris St. Cloud', full_street_address: '114 bis Avenue Michel Ange, 75016, Paris', meters_squared: 16, cost_per_month: 1900 })