class AddFieldsToOfficesTable < ActiveRecord::Migration
  	def change
  		add_column :offices, :office_description, :string
  		add_column :offices, :entry_fee, :integer
  		add_column :offices, :guarantee_deposit, :string
  		add_column :offices, :type_of_contract, :string
  		add_column :offices, :availability, :date
  		add_column :offices, :min_duration, :string
  		add_column :offices, :max_duration, :string
  		add_column :offices, :floor_number, :integer
  		add_column :offices, :has_elevator, :string
  		add_column :offices, :type_of_lighting, :string
  		add_column :offices, :type_of_office_space, :string
  		add_column :offices, :office_style, :string
  		add_column :offices, :server_access, :boolean
  		add_column :offices, :adsl, :boolean
  		add_column :offices, :rj45_cable, :boolean
  		add_column :offices, :fibre_optic, :boolean
  		add_column :offices, :dedicated_network, :boolean
  		add_column :offices, :wifi, :boolean
  		add_column :offices, :handicap_access, :boolean
  		add_column :offices, :air_conditioning, :boolean
  		add_column :offices, :cafeteria, :boolean
  		add_column :offices, :kitchen, :boolean
  		add_column :offices, :relaxation_room, :boolean
  		add_column :offices, :waiting_room, :boolean
  		add_column :offices, :cleaning_services, :boolean
  		add_column :offices, :eating_room, :boolean
  		add_column :offices, :storage, :boolean
  		add_column :offices, :television, :boolean
  		add_column :offices, :fax, :boolean
  		add_column :offices, :printer, :boolean
  		add_column :offices, :copy_machine, :boolean
  		add_column :offices, :individual_cupboard, :boolean
  		add_column :offices, :scanner, :boolean
  		add_column :offices, :tables_and_chairs, :boolean
  		add_column :offices, :telephone, :boolean
  		add_column :offices, :projector, :boolean
  		add_column :offices, :shared_assistant, :boolean
  		add_column :offices, :domiciliation, :boolean
  		add_column :offices, :free_parking, :boolean
  		add_column :offices, :paid_parking, :boolean
  		add_column :offices, :mail_reception, :boolean
  		add_column :offices, :receptionist, :boolean
  		add_column :offices, :shared_meeting_room, :boolean
  		add_column :offices, :paid_meeting_room, :boolean
  		add_column :offices, :private_meetin_room, :boolean
  		add_column :offices, :access_24_7, :boolean
  		add_column :offices, :badge_access, :boolean
  		add_column :offices, :alarm, :boolean
  		add_column :offices, :lockers, :boolean
  		add_column :offices, :independent_entrance, :boolean
  		add_column :offices, :company_name, :string
  		add_column :offices, :type_of_company, :string
  		add_column :offices, :company_activity, :string
  		add_column :offices, :company_status, :string
  		add_column :offices, :company_website, :string
  		add_column :offices, :company_description, :string
  	end
end
